### ISSUE TITLE
in Firefox 34.0.5 not working

### ISSUE THREAD

**Issue by monpy** [anvaka/wheel#1]
support is 'wheel' selected,
and event obj is this.
{
 [dom info],
 buttons: num, 
 clientX: num, 
 clientY: num,
 layerX: num, 
 layerY: num
}
support selected wrong?

**Comment by anvaka** [comment]
I'm sorry, I'm not following. What is broken?

I created this gist: http://requirebin.com/?gist=18a16b9e00f64d41f0fe I see in the console log entries when I use mouse wheel . Could you please elaborate?

**Comment by anvaka** [comment]
Resolving since haven't heard back. Please reopen if you can provide more details
