### ISSUE TITLE
removeWheelListener?

### ISSUE THREAD

**Issue by hellopath** [anvaka/wheel#3]
Hi there!

Is there a reason that no removeWheelListener implemented?

Thanks
Panos

**Comment by anvaka** [comment]
Hi Panos,

No particular reason. I just didn't need it, but I understand some people may need it.

Do you want to send a pull request? If so - I'd be glad to accept it. Otherwise I can fix it too when I have a little bit more time to spare.

**Comment by anvaka** [comment]
should be resolved with https://github.com/anvaka/wheel/pull/4

Thank you!
