### ISSUE TITLE
mdoule is not defined / typo in source?

### ISSUE THREAD

**Issue by jamespantalones** [anvaka/wheel#5]
Hello, I'm getting a a `mdoule is not defined` error in my console when using the plugin via CommonJS require. In the wheel `index.js` file, I'm seeing:
    `mdoule.exports.addWheelListener = addWheelListener;`
    `mdoule.exports.removeWheelListener = removeWheelListener;`

typo?

thanks

**Comment by anvaka** [comment]
Thank you very much for reporting this!

**Comment by jamespantalones** [comment]
no prob. thanks for the plugin
